#!/usr/bin/env php

<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\CreateHelloCommand;



$app = new Application('Console Test', 1.0);

$app->add(new CreateHelloCommand());

$app->run();